// stencil-app/src/components/app-form/app-form.tsx
import { Component, Event, EventEmitter, h, State } from '@stencil/core';
import type { Transaction } from '../../../../vanilla-app/src/types';

@Component({
  tag: 'app-form',
  styleUrl: 'app-form.css',
  shadow: true,
})
export class AppForm {
  @State() title = '';
  @State() amount = '';

  @Event() submit: EventEmitter<Transaction>;

  handleSubmit(event: Event) {
    event.preventDefault();
    this.submit.emit({
      title: this.title,
      amount: Number(this.amount),
    });
    this.title = '';
    this.amount = '';
  }

  render() {
    return (
      <div>
        <form id="create-transaction-form" onSubmit={this.handleSubmit.bind(this)}>
          <div class="inputs">
            <input type="text" name="title" placeholder="Título..." value={this.title} onInput={e => (this.title = (e.currentTarget as HTMLInputElement).value)} />
            <input type="number" name="amount" placeholder="Valor" step="1" value={this.amount} onInput={e => (this.amount = (e.currentTarget as HTMLInputElement).value)} />
          </div>
          <button type="submit">Adicionar</button>
        </form>
        <div class="form-helper-text">Use valores positivos para receitas e negativos para despesas.</div>
      </div>
    );
  }
}

// angular-app/src/app/app-form/app-form.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-form',
  templateUrl: './app-form.component.html',
  styleUrls: ['./app-form.component.css'],
})
export class AppFormComponent {
  title = '';
  amount = '';

  handleSubmit() {
    console.log('SUBMIT!');
  }
}

<form id="create-transaction-form" (submit)="handleSubmit">
  <div className="inputs">
    <input
      type="text"
      name="title"
      [(ngModel)]="title"
      placeholder="Título..."
    />
    <input
      type="number"
      name="amount"
      [(ngModel)]="amount"
      placeholder="Valor"
      step="1"
    />
  </div>
  <button type="submit">Adicionar</button>
</form>
