// svelte-app/src/Form.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import type { Transaction } from '../../vanilla-app/src/types'

  const dispatch = createEventDispatcher<{
    submit: Transaction
  }>()

  // STATES
  let title = ''
  let amount = ''

  function handleSubmit() {
    dispatch('submit', {
      title,
      amount: Number(amount),
    })
    title = ''
    amount = ''
  }
</script>

<form id="create-transaction-form" on:submit|preventDefault={handleSubmit}>
  <div class="inputs">
    <input
      type="text"
      name="title"
      bind:value={title}
      placeholder="Título..."
    />
    <input
      type="number"
      name="amount"
      bind:value={amount}
      placeholder="Valor"
      step="1"
    />
  </div>
  <button type="submit">Adicionar</button>
</form>

// vue-app/src/Form.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { Transaction } from '../../vanilla-app/src/types'

const emit = defineEmits<{
  (e: 'submit', values: Transaction): void
}>()

// STATES
const title = ref('')
const amount = ref('')

function handleSubmit() {
  emit('submit', {
    title: title.value,
    amount: Number(amount.value),
  })
  title.value = ''
  amount.value = ''
}
</script>

<template>
  <form id="create-transaction-form" @submit.prevent="handleSubmit">
    <div class="inputs">
      <input type="text" name="title" v-model="title" placeholder="Título..." />
      <input
        type="number"
        name="amount"
        v-model="amount"
        placeholder="Valor"
        step="1"
      />
    </div>
    <button type="submit">Adicionar</button>
  </form>
  <div class="form-helper-text transactions">
    Use valores positivos para receitas e negativos para despesas.
  </div>
</template>
